name: Deploy to VPS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to VPS
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/roundcall-backend-v2
            git pull origin main

            # Create or update .env file
            cat > .env << EOL
            MONGODB_URL=${{ secrets.MONGODB_URL }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            ENVIRONMENT=production
            EOL

            docker-compose down
            docker-compose up -d --build
